#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TransitApp.Droid.Resource", IsApplication=true)]

namespace TransitApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int MvxSource = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int border = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int srl_1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int srl_2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int srl_3 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int srl_4 = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int standard_background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drawer_shadow_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawer_shadow_light = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_new = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_overflow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_drawer_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_edit = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_refresh = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Train_1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Train_2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Train_3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Train_4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Train_5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Train_5X = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Train_6 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Train_6X = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Train_7 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Train_7x = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Train_A = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Train_B = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Train_C = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Train_D = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Train_E = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Train_F = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Train_G = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Train_GS = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Train_J = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Train_L = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Train_M = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Train_N = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Train_Q = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Train_R = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Train_S = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Train_Z = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int Area = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int Destination = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int MvxBindingTagUnique = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int StationName = 2131099651;
			
			// aapt resource value: 0x7f06000a
			public const int content_frame = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int drawer_layout = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int empty = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int icons = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int image = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int item_img = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int left_drawer = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int menu_done = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int menu_edit = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int menu_new = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int menu_refresh = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int search_text = 2131099660;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int time = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int item_columns = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_alerts = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int item_alert = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int item_follow = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int item_followLine = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int item_lineIcon = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int item_lineIcon2 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int item_menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int item_train = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int page_followEdit_view = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int page_follows_view = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int page_home_view = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int page_search = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SplashScreen = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int alert = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int followEdit = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int follows = 2131296258;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int cancel = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int drawer_close = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int drawer_open = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int menu_done = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int menu_edit = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int menu_new = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int menu_refresh = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int ok = 2131165191;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Theme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Theme_Splash = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
